services:
  postgres:
    image: postgres:${POSTGRES_VERSION?}
    container_name: postgres
    restart: unless-stopped
    user: "0:0"
    environment:
      POSTGRES_USER: ${POSTGRES_USER?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?}
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'postgres' ]
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - pg_network
    labels:
      org.label-schema.group: "postgres"

  postgres_exporter:
    image: bitnami/postgres-exporter:latest
    container_name: postgres_exporter
    restart: unless-stopped
    user: "0:0"
    depends_on:
      - postgres
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
    networks:
      - pg_network
    ports:
      - "9187:9187"
    labels:
      org.label-schema.group: "postgres"